app.config(['$routeProvider',function($l){
    $l.when('/',{
        templateUrl:'pages/index/index.html'
    }).when('/dls',{
        templateUrl:'pages/dls/index.html'
    }).when('/sqrz',{
        templateUrl:'pages/sqrz/index.html'
    })
}])