app.config(['$routeProvider',function($l){
    $l.when('/',{
        templateUrl:'pages/index/index.html'
    }).when('/dls',{
        templateUrl:'pages/dls/index.html'
    }).when('/sqrz',{
        templateUrl:'pages/sqrz/index.html'
    }).when('/dlsxq/:id',{
        templateUrl:'pages/dlsxq/index.html'
    }).when('/jgjg',{
        templateUrl:'pages/jgjg/index.html'
    }).when('/jgjgxq/:id',{
        templateUrl:'pages/jgjgxq/index.html'
    }).when('/new/:id',{
        templateUrl:'pages/new/index.html'
    })
}])