var dlsxq = angular.module('dlsxq',['ngRoute']);
dlsxq.directive('dlsxqCall',function(){
    return{
        restrict:'ECMA',
        templateUrl:'tpls/dlsxqCall.html',
        replace:true,
        scope:{
            tit:"@tit",
            con:"@con"
        }
    }
});
var dlsxqArr = [
    {
        id:1,
        url:'dlsxq.png',
        money:'8$',
        love:'有纯ECN PRO的可开工的是',
        title:'Imsforex'
    },
    {
        id:2,
        url:'dls_07.png',
        money:'18$',
        love:'抱财网 科技Sprovice Disk',
        title:'Provider'
    },
    {
        id:3,
        url:'dlsxq.png',
        money:'2$',
        love:'你有你的收到货的S provider',
        title:'configSvo'
    },
    {
        id:4,
        url:'s9.png',
        money:'1$',
        love:'FXCM 你的独特信息定制者及师',
        title:'SpiansolLov'
    }
]
dlsxq.controller('dlsxq',function($scope){
    $scope.dlsxqArr=dlsxqArr;
})
var ly =[
    {
        id:1,
        con:'我是第一个留言我是第一个留言',
        time:'2016年5月',
        sec:[
            {
            id:1,
            con:'我是第一条二级回复1',
            name:'APP'
            },
            {
            id:2,
            con:'我是第一条二级回复2',
            name:'冯晋环'    
            },
            {
            id:3,
            con:'我是第一条二级回复3',
            name:'无名剑客'    
            }
        ]
    },
    {
        id:2,
        con:'我是第二个留言我是第二个留言我是第二个留言我是第二个留言',
        time:'2016年6月',
        sec:[]
    }
]
dlsxq.controller('ly',function($scope){
    $scope.flag='block';
    $scope.num=2;
    $scope.ly=ly;
    $scope.lyb='';
    $scope.add=function(e){
        if($scope.lyb){
            $scope.ly.push({
                id:e+1,
                con:$scope.lyb,
                time:new Date().getTime(),
                sec:[]
            });
            localStorage.lyb=$scope.lyb;
            $scope.lyb='';
       } 
    };
    $scope.sec=function(e){
        if($scope.lyb){
           $scope.ly[e].sec.push({
               con:$scope.lyb,
               name:'匿名回复'
           });
           $scope.lyb='';
       } 
       console.log($scope.ly[e].sec)
    }
    $scope.more=function(e){
        $scope.flag='none';
        $scope.num=100;
    }
})